### ISSUE TITLE
SWF support

### ISSUE THREAD

**Issue by GonzalezAtWork** [Next2D/player#165]
is this still usable/possible to work with .swf (flash) files?
or that was dropped from swf2js?

**Comment by ienaga** [comment]
@GonzalezAtWork 
No, we do not have any SWF files. Some SWF files can be read, but Next2D does not work with swf2js.

**Comment by GonzalezAtWork** [comment]
so how can I get in touch with the sells team of swf2js to get the latest release prod version?

**Comment by ienaga** [comment]
@GonzalezAtWork 
swf2js productions are no longer available.

**Comment by GonzalezAtWork** [comment]
> @GonzalezAtWork swf2js productions are no longer available.

so, no way to get that "production" version running AVM2? sad :'(
