### ISSUE TITLE
Implementation of sockets

### ISSUE THREAD

**Issue by Azshurith** [Next2D/player#29]
Will you implement sockets?

**Comment by ienaga** [comment]
Hello.
What specific features are you expecting?

Next2D distributes the roles into three categories.
The Next2D framework is for game development that matches the scale of development, such as DDD, MVVM, clean architecture, etc. The Next2D NoCode Tool is for intuitive animation.
Next2D player aims to render games and animations created with the above tools at high speed.

I know that WebSocket and socketio are well-known for sockets, but I would be glad to know what you have in mind.

**Comment by Azshurith** [comment]
I have a small MMORPG game that runs in flash, It currently uses the flash socket library (flash.net.Socket) for multiplayer. Most of the assets are loaded as an external SWF such as (maps, items, monsters). We would like to migrate in this platform.

**Comment by ienaga** [comment]
Thank you for your consideration.

We do not have the ability to smoothly convert SWF in Flash.
But we hope to provide as much information as possible.

In response to your first question, the socket function is supposed to use WebSocket, a standard JavaScript function.
If it is in JavaScript, no libraries are required, and it can be implemented as follows.

```
const socket = new WebSocket('ws://url');
// open event
socket.addEventListener('open', (event) => {
    // メッセージを送信
    socket.send('Hello Server!');
});

// メッセージの待ち受け
socket.addEventListener('message', (event) => {
    console.log('Message from server ', event.data);
});
```

If you are expecting a swf2js-like conversion, I am sorry, but I don't think Next2D can handle it.

**Comment by ienaga** [comment]
If you have any questions, please contact us anytime :)
